# Generated by Django 6.1.1 on 2026-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invite_code',
            field=models.CharField(default='i3lANNzVLVY', editable=False, max_length=20, unique=True),
        ),
    ]
