# Generated by Django 6.1.1 on 2026-09-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invite_code',
            field=models.CharField(default='6Zp20f0_leI', editable=False, max_length=20, unique=True),
        ),
    ]
