# Generated by Django 6.1.1 on 2026-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invite_code',
            field=models.CharField(default='AY04rcsf0oA', editable=False, max_length=20, unique=True),
        ),
    ]
