# Generated by Django 6.1.1 on 2026-09-18 05:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
