# Generated by Django 6.1.1 on 2026-09-18 06:11

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_invite_code'),
        ('documents', '0003_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
